openapi: 3.0.1
info:
  title: '@jupiterone/peril'
  description: Project Risk Analysis and Reporting Tool
  x-cortex-git:
    github:
      repository: JupiterOne/peril
  x-cortex-owners:
    - type: group
      name: JupiterOne/sre
  x-cortex-tag: '@jupiterone/peril'
  x-cortex-service-groups:
    - tier-4
